Event loop friendly node 6
bbc/serverless-catbox-memory pull request #1
Opened 2017-10-05 10:26 UTC by subvertnormality

Removes usage of setTimouts to expire cache, and instead expires cache items on fetch/set.

2017-10-10 12:09 UTC, subvertnormality commented
retest this please

2017-10-16 11:13 UTC, azizur requested changes
Some comment/change request from me. Interested in hearing your thoughts.

2017-10-16 11:13 UTC, azizur commented on package.json
> +    "node": ">=4.0.0"
Why not node 6?
We need to check it on node 6, we do not need to support anything below 6.

2017-10-16 11:13 UTC, azizur commented on package.json
> +  "version": "2.0.4",
Any reason why the version is starting at 2?

2017-10-16 11:13 UTC, azizur commented on .nvmrc
> +6.10.2
`No newline at end of file`

2017-10-16 11:13 UTC, azizur commented on lib/index.js
> +        return callback(null, null);
What are the two params in `callback(null, null);`? Is it `error, result`?
Do we need to return `null`'s because further down you are not returning null for the result?

2017-10-16 11:13 UTC, azizur commented on lib/index.js
> +        return this.drop(key, () => {
How about a oneliner`return this.drop(key, () => callback(null, null));`?

2017-10-16 11:13 UTC, azizur commented on lib/index.js
> +    }
Have we got linter setup in this project?

2017-10-16 11:13 UTC, azizur commented on lib/index.js
> +            return callback(new Error('Cache size limit reached'));
Perhaps a bit more explicit error message here. `Unable to store cache entry, cache size limit reached`?

2017-10-16 11:13 UTC, azizur commented on makefile
> +	docker run -t --rm --name $(DOCKER_IMAGE_NAME) -v $(PWD):/usr/src/app -v $(ETC_PKI_PATH):/etc/pki -w /usr/src/app node:$(NODE_VERSION) bash -c "make test"
`No newline at end of file`

2017-10-16 11:13 UTC, azizur commented on test/index.js
> +        const fn = () => {
Oneliner `const fn = () => Memory();`

2017-10-16 12:41 UTC, subvertnormality commented on lib/index.js
> +        return callback(null, null);
Honestly I think leaving the argument blank would perform the same function, but the rest of the code base has been explicit with passing `null` so I have remained consistent.

2017-10-16 13:41 UTC, subvertnormality commented on package.json
> +  "version": "2.0.4",
Version 3 of catbox-memory is Node 8 enabled - 2 is the Node 4 - 6 version.

2017-10-16 13:43 UTC, subvertnormality commented
@azizur actions implemented - please could you recheck?

2017-10-16 15:32 UTC, azizur approved these changes

2017-10-16 15:33 UTC, merged